version: '3.5'
services:
   minio:
       image: quay.io/minio/minio:RELEASE.2022-10-24T18-35-07Z
       command: server --console-address ":9001" /data
       volumes:
          - ./data:/data
          - ./config:/root/.minio
       environment:
          - MINIO_ROOT_USER=minioadmin
          - MINIO_ROOT_PASSWORD=uikui5choRith0ZieV2zohN5aish5r
          - MINIO_DOMAIN=minio.mydomain.com
          - MINIO_SERVER_URL=https://minio.mydomain.com
          - MINIO_BROWSER_REDIRECT_URL=https://console.minio.mydomain.com
       labels:
          - "traefik.enable=true"
          # Console
          - "traefik.http.routers.minio-console.rule=Host(console.minio.mydomain.com)"
          - "traefik.http.routers.minio-console.entrypoints=websecure"
          - "traefik.http.routers.minio-console.tls.certresolver=alpn"
          - "traefik.http.routers.minio-console.service=minio-console"
          - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
          # APi
          - "traefik.http.routers.minio.rule=Host(minio.mydomain.com)"
          - "traefik.http.routers.minio.entrypoints=websecure"
          - "traefik.http.routers.minio.tls.certresolver=alpn"
          - "traefik.http.routers.minio.service=minio"
          - "traefik.http.services.minio.loadbalancer.server.port=9000"

   mc:
       image: minio/mc
       depends_on:
           - minio
       command: sleep 3600 # Ejecutar el contenedor de manera indefinida
       volumes:
           - ./config:/root/.mc
       environment:
           - MC_HOST=minio
           - MC_PORT=9000
           - MC_ACCESS_KEY=minioadmin
           - MC_SECRET_KEY=uikui5choRith0ZieV2zohN5aish5r

       # Crea un bucket llamado "my-bucket"
       # y carga un archivo llamado "file.txt" en el bucket
       # Puedes agregar cuantas secciones desees para crear y cargar más buckets.
       command: |
           mc mb my-bucket
           mc cp file.txt my-bucket/
