version: '3.5'
services:
  minio:
    image: quay.io/minio/minio:latest
#    container_name: minio-container
#    build: ./
    command: server --console-address ":9001" /data
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=uikui5choRith0ZieV2zohN5aish5r
      - MINIO_DOMAIN=s3.saiyans.com.ve
      - MINIO_SERVER_URL=https://s3.saiyans.com.ve
      - MINIO_BROWSER_REDIRECT_URL=https://console-minio.saiyans.com.ve
    labels:
      - "traefik.enable=true"
      # Console
      - "traefik.http.routers.minio-console.rule=Host(`console-minio.saiyans.com.ve`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=lets-encr"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      # APi
      - "traefik.http.routers.minio.rule=Host(`s3.saiyans.com.ve`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=lets-encr"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
  mc:
    image: minio/mc:latest
    depends_on:
     - minio
    volumes:
     -  ./static-files-myhub:/static-files-myhub
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --quiet --api s3v4 myminio http://minio:9000 admin uikui5choRith0ZieV2zohN5aish5r;
      /usr/bin/mc mb myminio/myhub-bucket;
      /usr/bin/mc mb myminio/myhubdev-bucket;
      /usr/bin/mc mb myminio/grydd-dev-static;
      /usr/bin/mc mb myminio/grydd-static;
      /usr/bin/mc cp --recursive /static-files-myhub/myhubdev-bucket/ myminio/myhubdev-bucket;
      /usr/bin/mc cp --recursive /static-files-myhub/myhub-bucket/ myminio/myhub-bucket;
      /usr/bin/mc cp --recursive /static-files-myhub/grydd-static/ myminio/grydd-static;
      /usr/bin/mc cp --recursive /static-files-myhub/grydd-dev-static/ myminio/grydd-dev-static;
      /usr/bin/mc anonymous set public myminio/myhubdev-bucket;
      /usr/bin/mc anonymous set public myminio/myhub-bucket;
      /usr/bin/mc anonymous set public myminio/grydd-dev-static;
      /usr/bin/mc anonymous set public myminio/grydd-static;
      "

